# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Season.create(name: "2021-22")
Location.create(name: "Normal Homecourt", gmaps_url: "https://goo.gl/maps/GCHt21pgWYSbWZsw8", practice_court: false)
Location.create(name: "Practice Court 1", gmaps_url: "https://goo.gl/maps/GCHt21pgWYSbWZsw8", practice_court: true)
Location.create(name: "Practice Court 2", gmaps_url: "https://goo.gl/maps/GCHt21pgWYSbWZsw8", practice_court: true)
Location.create(name: "Practice Court 3", gmaps_url: "https://goo.gl/maps/GCHt21pgWYSbWZsw8", practice_court: true)
Location.create(name: "Practice Court 4", gmaps_url: "https://goo.gl/maps/GCHt21pgWYSbWZsw8", practice_court: true)
Division.create(name: "School")
Division.create(name: "Local")
Division.create(name: "Regional")
Division.create(name: "National")
Kind.create(name: "1x0")
Kind.create(name: "1x1")
Kind.create(name: "1x1+1")
Kind.create(name: "2x0")
Kind.create(name: "2x1")
Kind.create(name: "2x2")
Kind.create(name: "2x2+2")
Kind.create(name: "3x0")
Kind.create(name: "3x2")
Kind.create(name: "3x3")
Kind.create(name: "4x0")
Kind.create(name: "4x4")
Kind.create(name: "5x0")
Kind.create(name: "5x5")
Kind.create(name: "Conditioning")
Kind.create(name: "Rest")
Kind.create(name: "Play")
Kind.create(name: "Defense")
Kind.create(name: "System")
Skill.create(name: "Speed")
Skill.create(name: "Jump")
Skill.create(name: "Resistance")
Skill.create(name: "Strength")
Skill.create(name: "Dribble")
Skill.create(name: "Pass")
Skill.create(name: "Shot")
Skill.create(name: "Finishing")
Skill.create(name: "Defense")
Skill.create(name: "Rebound")
Skill.create(name: "Hand-off")
Skill.create(name: "Off-Ball Pick")
Skill.create(name: "On-Ball Pick")
Skill.create(name: "Blind Pick")
Skill.create(name: "Ball Handling")
Skill.create(name: "Pick & Roll")
Category.create(name: "Senior", sex: "Fem.", min_years: 15, max_years: 99)
Category.create(name: "Senior", sex: "Masc.", min_years: 15, max_years: 99)
Category.create(name: "U-18", sex: "Fem.", min_years: 15, max_years: 17)
Category.create(name: "U-18", sex: "Masc.", min_years: 15, max_years: 17)
Category.create(name: "U-16", sex: "Fem.", min_years: 13, max_years: 15)
Category.create(name: "U-16", sex: "Masc.", min_years: 13, max_years: 15)
Category.create(name: "U-14", sex: "Fem.", min_years: 11, max_years: 13)
Category.create(name: "U-14", sex: "Masc.", min_years: 11, max_years: 13)
Category.create(name: "U-12", sex: "Fem.", min_years: 9, max_years: 11)
Category.create(name: "U-12", sex: "Masc.", min_years: 9, max_years: 11)
Category.create(name: "U-12", sex: "Mixed", min_years: 9, max_years: 11)
Category.create(name: "U-10", sex: "Fem.", min_years: 6, max_years: 9)
Category.create(name: "U-10", sex: "Masc.", min_years: 6, max_years: 9)
Category.create(name: "U-10", sex: "Mixed", min_years: 6, max_years: 9)
Category.create(name: "Baby Basket", sex: "Mixed", min_years: 5, max_years: 7)
Team.create(name: "Senior Fem.", season_id: 1, category_id: 1, division_id: 3, homecourt_id: 1)
Team.create(name: "Senior Masc.", season_id: 1, category_id: 2, division_id: 3, homecourt_id: 1)
Team.create(name: "U-18 Fem.", season_id: 1, category_id: 3, division_id: 3, homecourt_id: 1)
Team.create(name: "U-18 Masc.", season_id: 1, category_id: 4, division_id: 3, homecourt_id: 1)
Team.create(name: "U-16 Fem.", season_id: 1, category_id: 5, division_id: 3, homecourt_id: 1)
Team.create(name: "U-16 Masc.", season_id: 1, category_id: 6, division_id: 3, homecourt_id: 1)
Team.create(name: "U-14 Fem.", season_id: 1, category_id: 7, division_id: 2, homecourt_id: 1)
Team.create(name: "U-14 Masc.", season_id: 1, category_id: 8, division_id: 3, homecourt_id: 1)
Team.create(name: "U-12 Fem.", season_id: 1, category_id: 9, division_id: 2, homecourt_id: 1)
Team.create(name: "U-12 Masc.", season_id: 1, category_id: 10, division_id: 3, homecourt_id: 1)
Team.create(name: "U-10 Fem.", season_id: 1, category_id: 12, division_id: 2, homecourt_id: 1)
Team.create(name: "U-10 Masc.", season_id: 1, category_id: 13, division_id: 3, homecourt_id: 1)
Team.create(name: "Baby Basket", season_id: 1, category_id: 15, division_id: 1, homecourt_id: 1)
